### Create Report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 125000,
    "make": "Audi",
    "model": "RS5",
    "year": 2007,
    "lng": 0,
    "lat": 0,  
    "mileage": 200000
}

### Approve Report
PATCH http://localhost:3000/reports/4
Content-Type: application/json

{
    "approved": true
}

### Get An Estimate For An Existing Vehicle
GET http://localhost:3000/reports?make=Audi&model=RS5&lng=0&lat=0&mileage=200000&year=2005